import carBreakdown from 'src/assets/svg/car-breakdown.svg';
import money from 'src/assets/svg/money.svg';
import towTruck from 'src/assets/svg/tow-truck.svg';
import carRecycle from 'src/assets/svg/car-recycle.svg';
import eco from 'src/assets/svg/ecology-and-environment.svg';
import telephone from 'src/assets/svg/telephone.svg';
import kilometersColored from 'src/assets/svg/kilometer-colored.svg';
import emergencyTriangle from 'src/assets/svg/emergency-triangle.svg';
import carBrokedown from 'src/assets/svg/car-brokedown.svg';
import softeloOriginalLogo from 'src/assets/logo/resizable_vector_files/original.svg';

export const CAR_BREAKDOWN = carBreakdown;
export const MONEY = money;
export const TOW_TRUCK = towTruck;
export const CAR_RECYCLE = carRecycle;
export const ECO = eco;
export const TELEPHONE = telephone;
export const EMERGENCY_TRIANGLE = emergencyTriangle;
export const KILOMETERS_COLORED = kilometersColored;
export const CAR_BROKEDOWN = carBrokedown;
export const SOFTELO_ORIGINAL_LOGO = softeloOriginalLogo;
